extends SceneTree

func _initialize() -> void:
	var repo := ProjectSettings.globalize_path("res://../..")
	var source_root := repo.path_join("assets/game/player/gunship-v1/sources")
	var original := Image.load_from_file(source_root.path_join("intact.png"))
	original.convert(Image.FORMAT_RGBA8)
	assert(original.get_pixel(0, 0).a == 0.0, "Intact master must have real transparency")
	var bounds := original.get_used_rect()
	var scale := 340.0 / maxf(bounds.size.x, bounds.size.y)
	var socket := Vector2(627, 575) * original.get_width() / 1280.0
	var target_size := Vector2i(roundi(original.get_width() * scale), roundi(original.get_height() * scale))
	var offset := Vector2i(Vector2(192, 256) - socket * scale)
	for state in ["intact", "damaged", "critical"]:
		var frame := original.duplicate()
		if state != "intact":
			var variant := Image.load_from_file(source_root.path_join(state + ".png"))
			variant.convert(Image.FORMAT_RGBA8)
			variant.resize(original.get_width(), original.get_height(), Image.INTERPOLATE_LANCZOS)
			# Shared silhouette mask fixes the generated checkerboard and guarantees stable edges.
			# Keep original edge pixels; only aligned interior armor uses the damage variant.
			for y in range(bounds.position.y + 6, bounds.end.y - 6):
				for x in range(bounds.position.x + 6, bounds.end.x - 6):
					var opacity := original.get_pixel(x, y).a
					for sample in [Vector2i(-6,0), Vector2i(6,0), Vector2i(0,-6), Vector2i(0,6)]:
						opacity = minf(opacity, original.get_pixel(x + sample.x, y + sample.y).a)
					if opacity < 0.99: continue
					var color := variant.get_pixel(x, y)
					color.a = original.get_pixel(x, y).a
					frame.set_pixel(x, y, color)
		frame.resize(target_size.x, target_size.y, Image.INTERPOLATE_LANCZOS)
		var canvas := Image.create_empty(384, 512, false, Image.FORMAT_RGBA8)
		canvas.blit_rect(frame, Rect2i(Vector2i.ZERO, frame.get_size()), offset)
		_save(canvas, "res://assets/player_ship/gunship/" + state + ".png")
		_save(canvas, repo.path_join("assets/game/player/gunship-v1/frames-cell/" + state + ".png"))
		print(state, " alpha bounds=", canvas.get_used_rect())
	var turret := Image.load_from_file(source_root.path_join("railgun.png"))
	turret.convert(Image.FORMAT_RGBA8)
	assert(turret.get_pixel(0,0).a == 0.0)
	var turret_scale := 162.0 / (583.0 * turret.get_height() / 1280.0)
	var pivot := Vector2(627, 752) * turret.get_width() / 1280.0
	turret.resize(roundi(turret.get_width() * turret_scale), roundi(turret.get_height() * turret_scale), Image.INTERPOLATE_LANCZOS)
	var canvas := Image.create_empty(384, 512, false, Image.FORMAT_RGBA8)
	canvas.blit_rect(turret, Rect2i(Vector2i.ZERO, turret.get_size()), Vector2i(Vector2(192,256) - pivot * turret_scale))
	_save(canvas, "res://assets/player_ship/gunship/railgun.png")
	_save(canvas, repo.path_join("assets/game/player/gunship-v1/frames-cell/railgun.png"))
	var old := Image.load_from_file(ProjectSettings.globalize_path("res://assets/player_ship/player_ship_idle.png"))
	var old_visible_height := float(old.get_used_rect().size.y) / old.get_height() * 97.92
	var render_height := old_visible_height / (bounds.size.y * scale / 512.0)
	var left := Vector2(506,1110) * original.get_width() / 1280.0 * scale + Vector2(offset)
	var right := Vector2(770,1110) * original.get_width() / 1280.0 * scale + Vector2(offset)
	var data := FileAccess.open("res://scripts/systems/gunship_anchors.gd", FileAccess.WRITE)
	data.store_string("extends RefCounted\n# Generated by import-gunship-art.gd from shared source-space anchors.\nconst HEIGHT := %.4f\nconst ENGINES := [Vector2(%.3f, %.3f), Vector2(%.3f, %.3f)]\n" % [render_height,left.x,left.y,right.x,right.y])
	print("Gunship height=",render_height," engines=",left, right)
	quit()

func _save(image: Image, path: String) -> void:
	DirAccess.make_dir_recursive_absolute(path.get_base_dir())
	assert(image.save_png(path) == OK)
